---
- include: facts.yml
- include: mail.yml
  tags: mail

- include: logrotate.yml
- include: jq.yml
  tags: service_ips

- include: gem.yml

- include: bashrc.yml
- include: ntp.yml
  tags: ntp

- include: sensu.yml
  tags:
    - sensu-client
    - monitoring-client
  when: "'monitoring' in groups"

- include: sensu_config.yml
  tags:
    - sensu-client
    - monitoring-client
  when: "'monitoring' in groups"

- include: systemd.yml
  tags:
    - monitoring-client

- include: collectd.yml
  tags:
    - collectd
    - graph-client
  when: "'monitoring'"

- include: collectd_config.yml
  tags:
    - collectd
    - graph-client
  when: "'monitoring' in groups"
