---
- yum: name=ntp state=installed

- template:
    src: ../../templates/etc/ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644

- service: name=ntpd state=running enabled=yes

- name: set timezone
  file:
    state: link
    dest: /etc/localtime
    src: "/usr/share/zoneinfo/{{ timezone }}"
