---

- name: Add openshift-monitoring-client service file
  template:
    src: ../../templates/etc/systemd/system/openshift-monitoring-client.service.j2
    dest: /etc/systemd/system/openshift-monitoring-client.service
    mode: 0644
  when: "'monitoring' in groups"
  notify: systemctl daemon-reload
