---
- include: sensu_config.yml
  tags: monitoring-client
  when: "'monitoring' in groups and dockerbuild is undefined"

- include: sensu.yml
  tags: monitoring-client
  when: "'monitoring' in groups"
