---
deployment_type: "origin"
sensu_manage_docker_storage: "{{ manage_docker_storage | default('true') }}"

sensu_deployment_type: "{{ deployment_type | default('openshift') }}"

sensu_openshift_etc_config: "{% if deployment_type == 'origin' or deployment_type == 'openshift-enterprise' %}origin{% else %}openshift{% endif %}"

sensu_openshift_base_api: "{{ openshift_base_api | default('/api/v1/') }}"


sensu_openshift_master_cluster_method: "{{ openshift_master_cluster_method | default('pacemaker') }}"

#sensu_openshift_masters_deamon_name: "{% if deployment_type == 'origin' %}origin-master{% elif deployment_type == 'openshift-enterprise' %}atomic-openshift-master{% else %}openshift-master{% endif %}{% if sensu_openshift_master_cluster_method == 'native' %}-api{% endif %}"
#sensu_openshift_masters_deamon_name_controllers: "{% if deployment_type == 'origin' %}origin-master{% elif deployment_type == 'openshift-enterprise' %}atomic-openshift-master{% else %}openshift-master{% endif %}{% if sensu_openshift_master_cluster_method == 'native' %}-controllers{% endif %}"
